# API_KEY情報
API_KEY = 'API_KEY'
API_SECRET = 'API_SECRET'
ACCESS_TOKEN = 'ACCESS_TOKEN'
ACCESS_TOKEN_SECRET = 'ACCESS_TOKEN_SECRET'
BEARER_TOKEN = 'BEARER_TOKE'


# 次のワードを含むツイートをしたアカウント情報を
SERCH_WORD = 'ポケモン'
# 次のアカウント数分取得し
COUNT_USERS = 100
# それぞれ次のツイート数分取得
COUNT_TWEETS_EACH = 10